### ISSUE TITLE
shutil.copyfile(src, dst) not working 

### ISSUE THREAD

**Issue by sarmadm** [vishal-burman/Dogs_vs_Cats-CNN-Experimentation-#1]
Below part is not working , it is showing no such a file or directory ,

`fnames=['dog.{}.jpg'.format(i) for i in range(1000)]
for fname in fnames:
    src=os.path.join(original_dataset_dir, fname)
    dst=os.path.join(train_dogs_dir, fname)
    shutil.copyfile(src, dst)`

it is showing src and dst images when I use print(src) , print (dst),  any idea ?

**Comment by vishal-burman** [comment]
try to look at the paths of the dataset and set it according to your preference. It is set to default folder names as given by me therefore it wont work for you.
